<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="L-SJC-10005066" name="searchMovies" tests="1" failures="1" timestamp="13 Feb 2017 04:10:02 GMT" time="1.011" errors="0">
  <testcase name="TestValidateResponse" time="0.955" classname="rest.automation.netflix.TestClass">
    <failure type="java.lang.AssertionError" message="unit not matches expected [35] but found [352]">
      <![CDATA[java.lang.AssertionError: unit not matches expected [35] but found [352]
	at rest.automation.netflix.TestClass.validateResponse(TestClass.java:68)
	at rest.automation.netflix.TestClass.TestValidateResponse(TestClass.java:46)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TestValidateResponse -->
</testsuite> <!-- searchMovies -->
